version: '3.8'
services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_PHP
    build: php
    volumes:
      - ./api:/var/www/html

  database:
    container_name: ${COMPOSE_PROJECT_NAME}_PGSQL
    image: ${PGSQL_IMAGE}
    environment:
      POSTGRES_DB: kwizz
      POSTGRES_PASSWORD: root
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "55432:5432"

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_NGINX
    build:
      context: ./nginx
    volumes:
      - ./api:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data: